### ISSUE TITLE
Release 2.11.1.0

### ISSUE THREAD

**Issue by vooon** [Aiven-Open/prometheus-exporter-plugin-for-opensearch#238]
OpenSearch 2.11.1 has been released, see [release notes](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.11.1.md).
Official OpenSearch release ticket: https://github.com/opensearch-project/opensearch-build/issues/4161

Checklist:

- [x] [Compatibility Matrix](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch#compatibility-matrix) is updated (https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/pull/241)
- [x] Release [2.11.1.0 tag](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/tag/2.11.1.0) is present in the repo
- [x] Release artifacts are available and downloadable
- [x] [Release notes](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/tag/2.11.1.0) published
- [x] [Forum announcement](https://forum.opensearch.org/t/prometheus-exporter-plugin-2-11-1-0-released/16969) published

**Comment by lukas-vlcek** [comment]
OpenSearch upgrade PR is here: https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/pull/239, this needs to go first.

**Comment by lukas-vlcek** [comment]
Done.
