### ISSUE TITLE
Release 2.12.0

### ISSUE THREAD

**Issue by cesium147** [Aiven-Open/prometheus-exporter-plugin-for-opensearch#251]
OpenSearch 2.12.0 has been released, see [release notes](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.12.0.md).
Official OpenSearch release ticket: https://github.com/opensearch-project/opensearch-build/issues/4115

Checklist:

- [x] [Compatibility Matrix](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch#compatibility-matrix) is updated (#255)
- [x] Release [2.12.0.0 tag](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/tag/2.12.0.0) is present in the repo
- [x] Release artifacts are available and downloadable
- [x] [Release notes](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/tag/2.12.0.0) published
- [x] Forum announcement published

**Comment by lukas-vlcek** [comment]
Forum post: https://forum.opensearch.org/t/prometheus-exporter-plugin-2-12-0-0-released/18105
