### ISSUE TITLE
opensearch_os_cpu_percent and opensearch_process_cpu_percent don't appear to report correct values

### ISSUE THREAD

**Issue by drewmiranda-gl** [Aiven-Open/prometheus-exporter-plugin-for-opensearch#267]
There is a discrepancy in what this exporter reports and what the legacy `elasticsearch-exporter` reports. This exporter also doesn't appear to reconcile with the actual cpu usage or load seen either directly on the server/vm or via node_exporter.

Examples:

<img width="954" alt="image" src="https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/assets/107503402/66f878eb-63ed-4cff-b262-1f24703e8b4c">

Above the cpu usage of the server does appear to be about 40% which matches when compared to node_expoter. However in this chart, the usage is very low for most of the graph (which appears to be wrong and too low), There is no explanation about why the chart is displaying a value that is too low and then suddenly appears to start reflecting more correct values.

compare with node_expoter cpu usage for the same server and time range:
<img width="632" alt="image" src="https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/assets/107503402/d062b904-061d-41cf-8ace-617f85fa3ef7">

notice this chart is much more stable and consistent, as i would expect it to be.

The below chart from elasticsearch-expoter also does appear more accurate and correct. It is consistent and doesn't have any points where it is reporting a number that is too low or too high (that doesn't match up with the actual usage or metrics of the server)

<img width="647" alt="image" src="https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/assets/107503402/72132ca6-385d-42a0-8e1f-b3e81de044cf">

`opensearch_process_cpu_percent` also strangely shows a huge jump to ~100% which seems wrong and cannot be verified by any other metrics:

<img width="954" alt="image" src="https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/assets/107503402/f2dbdbbd-4283-471e-9e2e-865b0052aa18">

Let me know if there is any info I can provide or variables.

Using OpenSearch 2.12 and version 2.12 of this plugin. VM has 2 vCPU and 18GB ram (8GB heap)

**Comment by lukas-vlcek** [comment]
@drewmiranda-gl Did you figure out what was wrong? Is there anything that can be improved on the documentation side?

**Comment by hagaram** [comment]
Im having exactly the same issue - node exporter seems completely fine, but CPU usage reported by OSE metrics is strange,
