### ISSUE TITLE
[DOCS] Missing the default value for `prometheus.cluster.settings`

### ISSUE THREAD

**Issue by lukas-vlcek** [Aiven-Open/prometheus-exporter-plugin-for-opensearch#297]
Add info about what the **default** value for `prometheus.cluster.settings` [plugin config](https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/blob/main/README.md#plugin-configuration) is.

**Comment by lukas-vlcek** [comment]
@spapadop Go for it!

**Comment by spapadop** [comment]
There you go https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/pull/318
