### ISSUE TITLE
Release 1.3.19.0

### ISSUE THREAD

**Issue by rpo-fr** [Aiven-Open/prometheus-exporter-plugin-for-opensearch#299]
OpenSearch 1.3.19 has been released, see [release notes](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-1.3.19.md).

Checklist:

- [x] [Compatibility Matrix](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch#compatibility-matrix) is updated (https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/pull/309)
- [x] Release [1.3.19.0 tag](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/tag/1.3.19.0) is present in the repo
- [x] Release artifacts are available and downloadable
- [x] [Release notes](https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/tag/1.3.19.0) published
- [x] [Forum announcement](https://forum.opensearch.org/t/prometheus-exporter-plugin-1-3-18-0-and-1-3-19-0-released/21634) published

**Comment by javsalgar** [comment]
I'm also missing version 1.3.18, which was released on 2024-07-09

**Comment by lukas-vlcek** [comment]
@javsalgar Opening a ticket for Release 1.3.18: https://github.com/Aiven-Open/prometheus-exporter-plugin-for-opensearch/issues/304
